### PR TITLE
ember-data 1.0.0-beta.15 compatibility

### PR DESCRIPTION
**Pull request by jakesjews**
I'm not 100% sure this is all thats needed, but this makes all tests pass and seems to work when dropped into our ember application.

### CODE REVIEW

**Comment by slindberg** [comment]
Ugh, relying on private APIs is the worst. Thanks for submitting this, I'm planning to upgrade our app this week, so I'll test this out in the next couple days.

**Comment by workmanw** [comment]
I should be able to test our app on Friday. Have to carve out a little time to update our serializers.

**Comment by MichaelLNorth** [comment]
I'll try this in one of our apps to help validate

**Comment by slindberg** [comment]
Closing in favor of #66 (I kept your commit @jakesjews).

@workmanw, @MichaelLNorth I pushed artifacts with snapshot compatibility updates to the [`tmp-dist`](https://github.com/lytics/ember-data.model-fragments/tree/tmp-dist) branch so you can test against it by updating your `bower.json`:

```json
{
  ...
  "dependencies": {
    "ember-data.model-fragments": "tmp-dist",
    ...
  }
}
```

**Comment by slindberg** [comment]
Note that [I've updated how snapshots handle fragments in #66](https://github.com/lytics/ember-data.model-fragments/pull/66#issuecomment-75131218).

**Pull request closed without merging**
